### ISSUE TITLE
master V5.18.1and Dash Wallet v5.17.5 build error

### ISSUE THREAD

**Issue by flyfishtina** [HashEngineering/dash-wallet#116]
C:\work\wallet\dash-wallet\native-scrypt\src\scrypt_platform.h
Information:(7) (Unknown) In file included
C:\work\wallet\dash-wallet\native-scrypt\src\scrypt_jni.c
Error:(3, 19) fatal error: errno.h: No such file or directory
C:\work\wallet\dash-wallet\native-scrypt\src\config.h
Error:(9, 24) fatal error: sys/limits.h: No such file or directory
Error:(9, 24) fatal error: sys/limits.h: No such file or directory
Error:Execution failed for task ':native-scrypt:compileScryptArmeabi-v7aDebugSharedLibraryScryptMainC'.
> Multiple build operations failed.
      C compiler failed while compiling crypto_scrypt-nosse.c.
      C compiler failed while compiling scrypt_jni.c.
      C compiler failed while compiling sha256.c.
  See the complete log at: file:///C:/work/wallet/dash-wallet/native-scrypt/build/tmp/compileScryptArmeabi-v7aDebugSharedLibraryScryptMainC/output.txt
Information:BUILD FAILED
Information:Total time: 4.366 secs
Information:4 errors
Information:0 warnings
Information:See complete output in console

I have downloaded master V5.18.1and Dash Wallet v5.17.5 .When build with studio It  always occurs the errors above, anyone could solve this issue?

**Comment by HashEngineering** [comment]
Use R12 for your native SDK version

**Comment by flyfishtina** [comment]
thx
