### ISSUE TITLE
NFC

### ISSUE THREAD

**Issue by theRealBitcoinClub** [HashEngineering/dash-wallet#128]
I would like to add NFC capabilities to the wallet.

Does that make sense or are you releasing a new wallet with evolution anyway?

How long would it take to integrate the pull request and release it on the Play Store?

**Comment by theRealBitcoinClub** [comment]
1. I created a NFC card with a dash address as only information something like, dash:KDhf793h...
2. I opened the wallet and i tapped the card (maybe that was the error as i have to be on the home screen?)
3. Nothing happened

But i will try that again and give you more feedback on the exact use case.

**Comment by HashEngineering** [comment]
Dash addresses begin with X.

Nevertheless, what you can do is try to use the NFC card, look for error messages, then send a Report with "Report Issue".  We can look at the app logs for an error message regarding the NFC string that the app is trying to use, but cannot.

**Comment by theRealBitcoinClub** [comment]
Thanks for the information.

Luckily i forgot to take the NFC cards with me to the place I work today, so testing will have to wait until tonight.

**Comment by HashEngineering** [comment]
I tried to test this feature between two phones, but nothing happened.  

Another one of our developers will be looking into this.  This feature did at one time work.

**Comment by tomasz-ludek** [comment]
Hi @theRealBitcoinClub,
thanks for your feedback.

I've tested the following use case (with [the latest official release](https://play.google.com/store/apps/details?id=hashengineering.darkcoin.wallet&hl=pl)):

1. Using [NFC Tools app](https://play.google.com/store/apps/details?id=com.wakdev.wdnfc&hl=pl) write the _Custom URL /URI_ (`dash:XnR3mVxB7U9TwDep7aUkx5qPme6qqhhTVo`) on an NFC Tag.
2. Close the _NFC Tools_ app
3. Scan recently programmed _NFC Tag_ with the phone (Dash Wallet doesn't have to be launched)
4. After reading _NFC Tag_ the _Send Dash_ screen is being openned, with payment address correctly filled in.

No issues found. Also tested with the amount parameter (`dash:XnR3mVxB7U9TwDep7aUkx5qPme6qqhhTVo?amount=1.23`)

Could you describe the issue you faced in more details?

Thanks

**Comment by theRealBitcoinClub** [comment]
If you believe it works now then everything is fine, maybe your developers silently fixed it exactly one day ago, as the owner of the repository had also issues using NFC 3 days ago.

**Comment by HashEngineering** [comment]
@theRealBitcoinClub 
I was using a faulty device in my testing.  NFC works between devices for requesting DASH.  That is to say, **sending Dash** from the app to an address which could be an app on another device or to a Dash address in an NFC tag.

In this post you made on the Dash Forum, https://www.dash.org/forum/threads/layout-bugs.40651/, you are taking about **spending Dash** from an NFC tag.  Another user was earlier this year offering a bounty for this functionality if it was added to the app (#82).  

If you are indeed asking about NFC tags with dumped private keys, then this app does not support that, though it has much of the backbone to support it.  It is basically a Paper Wallet Sweep that returns the change back into the NFC tags address.
