### ISSUE TITLE
Add setup to 'README.md' - Expected NDK STL shared object file

### ISSUE THREAD

**Issue by onedigital1** [HashEngineering/dash-wallet#248]
# Expected
Run the Android wallet module in Android Studio after cloning the repository.

# Observed
The following error occurs without installing the correct NDK-r15c first. Please add these instructions to the README.md.

# Solution

Install ndk-r15c:
```
mv ~/Android/Sdk/ndk-bundle ~/Android/Sdk/ndk-bundle-backup
wget https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip
unzip android-ndk-r15c-linux-x86_64.zip
mv android-ndk-r15c ~/Android/Sdk/ndk-bundle
```

Afterwards the error 

`"Please select Android SDK"`

can be fixed by syncing gradle via

`File -> Sync Project with gradle Files`

**Comment by HashEngineering** [comment]
On my system, I am using NDK 20 that is installed as part of the android SDK and would be here:  `~/Android/Sdk/ndk-bundle`

Of course this needs to be made more clear in the documentation PR #236.

**Comment by onedigital1** [comment]
NDK r17c didn't work for me, from the travis file I downgraded to NDK r15c, which works. Now I installed NDK 20 manually and it also works
