### ISSUE TITLE
Message signing, bitid feature request

### ISSUE THREAD

**Issue by gaby64** [HashEngineering/dash-wallet#32]

**Comment by HashEngineering** [comment]
There are no plans at this time to implement this feature.

**Comment by gaby64** [comment]
Any plans to atleast provide message signing capability?

**Comment by gaby64** [comment]
Please consider this once more, dash having the ability to do logins would be another plus for the community.

Mycelium wallet has it

https://github.com/mycelium-com/wallet-android/search?utf8=✓&q=bitid&type=
