### ISSUE TITLE
New Bitcoinaverage.com API URL

### ISSUE THREAD

**Issue by jalte** [HashEngineering/dash-wallet#38]
As of 19-June-2017 the version 1 of the Bitcoinaverage.com API has been switched off. https://github.com/bitcoinaverage/bitcoinaverage#19062017

The Dash wallet is now unable to get the exchange rate for many countries. 

The new API url is https://apiv2.bitcoinaverage.com/custom/abw. 

This should be updated at https://github.com/HashEngineering/dash-wallet/blob/d336093e43a6e158d72606235bcbb450e60a778e/wallet/src/de/schildbach/wallet/ExchangeRatesProvider.java#L122

**Comment by HashEngineering** [comment]
Thanks for pointing this out.  The version 5 update will fix this, I may update the current version with this fix.

**Comment by jalte** [comment]
Appreciate it if the update can be done on the current version as users in my country (Malaysia) are now unable to get the exchange rate for our Malaysian Ringgit. This causes problems for our daily use. Thanks.

**Comment by HashEngineering** [comment]
https://github.com/HashEngineering/dash-wallet/releases/tag/v4.65.12.1V - This link contains an update.  If you are able to install it on your device to make sure that the exchange rate you need is present, that would be great.  If I get positive feedback from you, I will publish to Google Play in 1-2 days.

**Comment by jalte** [comment]
Tested. The exchange rate is working as expected. 

![capture1](https://user-images.githubusercontent.com/10679072/27762346-bb88bec2-5ea2-11e7-8193-8a55656e9405.JPG)
![capture3](https://user-images.githubusercontent.com/10679072/27762359-133611e2-5ea3-11e7-96ac-332f8db1e35c.JPG)

**Comment by HashEngineering** [comment]
Thank you.  We have started to roll out this new update.
