### ISSUE TITLE
BUG: sweeping via camera crashes app

### ISSUE THREAD

**Issue by taw00** [HashEngineering/dash-wallet#4]
There are two ways to sweep a dash coin paper wallet.
1. Menu > Sweep paper wallet > Camera icon > scan, password, sweep
2. Camera from main screen > scan, password, CRASH!!!!

I have only tested this with password encrypted paper wallets, but it crashes using method #2.

Thanks. -t

**Comment by HashEngineering** [comment]
Thanks, we also found this bug on the "Dash IX Wallet Beta" - The User interface developer will start working on this today.

**Comment by joshafest** [comment]
hi 
is the bug still ??
i can try to remove it..

**Comment by HashEngineering** [comment]
In my testing this bug was fixed on the latest test version (Beta2).  What about for you?

**Comment by joshafest** [comment]
i was just asking if the bug is still there..

**Comment by HashEngineering** [comment]
The bug is still present.  We fixed another bug with scanning a QR code.  This is a bug that was present in Bitcoin Wallet as well.  However that bug was fixed.  We will need to import that change.

**Comment by joshafest** [comment]
ok ...so you are going to fix it yourself ....
or i should try?

**Comment by HashEngineering** [comment]
It appears that this may have been fixed on Bitcoin Wallet.  We need to the fix in, but it may take a while before we get to it.  If you would like to submit a pull request, you are welcome.

**Comment by HashEngineering** [comment]
We will be importing changes from Bitcoin Wallet in the next month or so to fix this.

**Comment by HashEngineering** [comment]
Version 4.65.12 and above have a fix for this issue.
