### ISSUE TITLE
com.hashengineering:dash-wallet-name-resolver

### ISSUE THREAD

**Issue by zss945** [HashEngineering/dash-wallet#58]
Where is the source code？

**Comment by zss945** [comment]
compile 'com.hashengineering:dash-wallet-name-resolver:0.1.4-12.1

**Comment by HashEngineering** [comment]
https://github.com/HashEngineering/dash-java-wns-resolver

**Comment by HashEngineering** [comment]
Bitcoin Wallet removed this component.  It has no use in Dash Wallet either.

**Comment by HashEngineering** [comment]
This feature will be removed from Dash Wallet in the near future.

**Comment by HashEngineering** [comment]
This wallet-name-resolver was removed from Bitcoin Wallet, we should also remove it.

**Comment by HashEngineering** [comment]
This feature will be removed in #188.

**Comment by HashEngineering** [comment]
This feature has been removed.
