### ISSUE TITLE
Improve security of handling `dashwallet://` uris

### ISSUE THREAD

**Issue by tomasz-ludek** [HashEngineering/dash-wallet#71]
1. Add a prompt in Dash Wallet when another app requests the master public key or an address using "dashwallet://..."  This is how the iOS app handles it and it will enhance the security of this feature.
2. Use `wallet.freshReceiveAddress()` instead of `wallet.currentReceiveAddress()` for address request.

**Comment by HashEngineering** [comment]
This issue was part of v5.17.5.

**Comment by HashEngineering** [comment]
https://github.com/HashEngineering/dash-wallet/commit/70d0cb286e4148d8b582f26b9c57dec0a69551c8
