### ISSUE TITLE
IOException on build APK with Proguard Enable

### ISSUE THREAD

**Issue by jaydeep82** [HashEngineering/dash-wallet#75]
Error:Execution failed for task ':wallet:transformClassesAndResourcesWithProguardFor_testNet3Debug'.
> java.io.IOException: Please correct the above warnings first.
Warning:Exception while processing task java.io.IOException: Please correct the above warnings first.
Warning:there were 7 unresolved references to classes or interfaces.
Warning:there were 115 instances of library classes depending on program classes.
Warning:retrofit2.Platform$Java8: can't find referenced class java.lang.invoke.MethodHandles$Lookup
Warning:retrofit2.Platform$Java8: can't find referenced class java.lang.invoke.MethodHandle
Warning:retrofit2.Platform$Java8: can't find referenced class java.lang.invoke.MethodHandles
Warning:retrofit2.Platform$Java8: can't find referenced class java.lang.invoke.MethodHandle

**Comment by HashEngineering** [comment]
Does this happen on our master branch?  We have not encountered this error using our current build configuration with several developers.

**Comment by jaydeep82** [comment]
We had fix that issue on wallofcoin branch using add this code in proguard.cfg 

-dontwarn okio.DeflaterSink
-dontwarn okio.Okio
-dontnote com.squareup.okhttp.internal.Platform
