### ISSUE TITLE
who can build the darkcoin-wallet？

### ISSUE THREAD

**Issue by ywzqhl** [HashEngineering/dash-wallet#8]
who can build the darkcoin-wallet? it seems lost some java packages

**Comment by HashEngineering** [comment]
I don't have a problem building this app.  What are you error messages?  

You have to build darkcoinj first using maven.

**Comment by ywzqhl** [comment]
yes,I build darkcoinj first using maven, and install the darkcoinj-core-0.13.2.ix.jar in the loacal repository,but still failed, the message as follows,please help me! or can you make a detail build approacch,thank you very much!

Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Windows\system32>d:

D:\>cd D:\thinkcoin\dbg\darkcoin-wallet-4.40.12g.ix

D:\thinkcoin\dbg\darkcoin-wallet-4.40.12g.ix>gradle clean build
To honour the JVM settings for this build a new JVM will be forked. Please consi
der using the daemon: http://gradle.org/docs/2.2/userguide/gradle_daemon.html.
:integration-android:clean
:sample-integration-android:clean
:wallet:cleanCopyNativeLibs UP-TO-DATE
:wallet:clean UP-TO-DATE
:integration-android:compileJava
警告: [options] 未与 -source 1.5 一起设置引导类路径
1 个警告
:integration-android:processResources UP-TO-DATE
:integration-android:classes
:integration-android:jar
:integration-android:assemble
:integration-android:compileTestJava UP-TO-DATE
:integration-android:processTestResources UP-TO-DATE
:integration-android:testClasses UP-TO-DATE
:integration-android:test UP-TO-DATE
:integration-android:check UP-TO-DATE
:integration-android:build
:sample-integration-android:preBuild UP-TO-DATE
:sample-integration-android:preDebugBuild UP-TO-DATE
:sample-integration-android:checkDebugManifest
:sample-integration-android:prepareDebugDependencies
:sample-integration-android:compileDebugAidl
:sample-integration-android:compileDebugRenderscript
:sample-integration-android:generateDebugBuildConfig
:sample-integration-android:generateDebugAssets UP-TO-DATE
:sample-integration-android:mergeDebugAssets
:sample-integration-android:generateDebugResValues UP-TO-DATE
:sample-integration-android:generateDebugResources
:sample-integration-android:mergeDebugResources
:sample-integration-android:processDebugManifest
:sample-integration-android:processDebugResources
:sample-integration-android:generateDebugSources
:sample-integration-android:processDebugJavaRes UP-TO-DATE
:sample-integration-android:compileDebugJavaWithJavac
D:\thinkcoin\dbg\darkcoin-wallet-4.40.12g.ix\sample-integration-android\src\de\s
childbach\wallet\integration\sample\SampleActivity.java:20: error:package org.bitc
oinj.core not exist
import org.bitcoinj.core.Address;
                        ^
D:\thinkcoin\dbg\darkcoin-wallet-4.40.12g.ix\sample-integration-android\src\de\s
childbach\wallet\integration\sample\SampleActivity.java:21: error:package org.bitc
oinj.core not exist
import org.bitcoinj.core.AddressFormatException;
                        ^
D:\thinkcoin\dbg\darkcoin-wallet-4.40.12g.ix\sample-integration-android\src\de\s
childbach\wallet\integration\sample\SampleActivity.java:22: error:package org.bitc
oinj.core not exist
import org.bitcoinj.core.NetworkParameters;
                        ^
D:\thinkcoin\dbg\darkcoin-wallet-4.40.12g.ix\sample-integration-android\src\de\s
childbach\wallet\integration\sample\SampleActivity.java:23: error:package org.bitc
oinj.script not exist
import org.bitcoinj.script.ScriptBuilder;
                          ^
D:\thinkcoin\dbg\darkcoin-wallet-4.40.12g.ix\sample-integration-android\src\de\s
childbach\wallet\integration\sample\SampleActivity.java:103:error:can't find symbol
                        final NetworkParameters params = Address.getParametersFr
omAddress(addresses[0]);
                              ^
 symbol:   class NetworkParameters
  location: class  SampleActivity
D:\thinkcoin\dbg\darkcoin-wallet-4.40.12g.ix\sample-integration-android\src\de\s
childbach\wallet\integration\sample\SampleActivity.java:103: error:can't find symbol
                        final NetworkParameters params = Address.getParametersFr
omAddress(addresses[0]);
                                                         ^
  symbol:   variable Address
  location: class  SampleActivity
D:\thinkcoin\dbg\darkcoin-wallet-4.40.12g.ix\sample-integration-android\src\de\s
childbach\wallet\integration\sample\SampleActivity.java:107:error:can't find symbol
                        output1.setScript(ByteString.copyFrom(ScriptBuilder.crea
teOutputScript(new Address(params, addresses[0])).getProgram()));

                   ^
  symbol:   class Address
  location: class  SampleActivity
D:\thinkcoin\dbg\darkcoin-wallet-4.40.12g.ix\sample-integration-android\src\de\s
childbach\wallet\integration\sample\SampleActivity.java:107: error:can't find symbol
                        output1.setScript(ByteString.copyFrom(ScriptBuilder.crea
teOutputScript(new Address(params, addresses[0])).getProgram()));
                                                              ^
  symbol:   variable ScriptBuilder
  location: class  SampleActivity
D:\thinkcoin\dbg\darkcoin-wallet-4.40.12g.ix\sample-integration-android\src\de\s
childbach\wallet\integration\sample\SampleActivity.java:111: error:can't find symbol
                        output2.setScript(ByteString.copyFrom(ScriptBuilder.crea
teOutputScript(new Address(params, addresses[1])).getProgram()));

                   ^
  symbol:   class  Address
  location: class  SampleActivity
D:\thinkcoin\dbg\darkcoin-wallet-4.40.12g.ix\sample-integration-android\src\de\s
childbach\wallet\integration\sample\SampleActivity.java:111: error:can't find symbol
                        output2.setScript(ByteString.copyFrom(ScriptBuilder.crea
teOutputScript(new Address(params, addresses[1])).getProgram()));
                                                              ^
  symbol:   variable ScriptBuilder
  location: class  SampleActivity
D:\thinkcoin\dbg\darkcoin-wallet-4.40.12g.ix\sample-integration-android\src\de\s
childbach\wallet\integration\sample\SampleActivity.java:125:  error:can't find symbol
                catch (final AddressFormatException x)
                             ^
  symbol:   class AddressFormatException
  location: class SampleActivity
11 errors
:sample-integration-android:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sample-integration-android:compileDebugJavaWithJavac
'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 47.354 secs

D:\thinkcoin\dbg\darkcoin-wallet-4.40.12g.ix>

**Comment by HashEngineering** [comment]
gradle is not finding the darkcoinj.

you have to build the release-0.13 branch of darkcoinj using:
mvn clean install -DSkipTests

then build the release-4 branch of darkcoin-wallet using gradle (be sure to disable tests).

**Comment by ywzqhl** [comment]
D:\darkcoin\darkcoin-wallet-release-4>gradle clean installDebug
To honour the JVM settings for this build a new JVM will be forked. Please consi
der using the daemon: http://gradle.org/docs/2.2/userguide/gradle_daemon.html.
:integration-android:clean
:sample-integration-android:clean
:wallet:cleanCopyNativeLibs UP-TO-DATE
:wallet:clean UP-TO-DATE
:integration-android:compileJava

:integration-android:processResources UP-TO-DATE
:integration-android:classes
:integration-android:jar
:sample-integration-android:preBuild UP-TO-DATE
:sample-integration-android:preDebugBuild UP-TO-DATE
:sample-integration-android:checkDebugManifest
:sample-integration-android:prepareDebugDependencies
:sample-integration-android:compileDebugAidl
:sample-integration-android:compileDebugRenderscript
:sample-integration-android:generateDebugBuildConfig
:sample-integration-android:generateDebugAssets UP-TO-DATE
:sample-integration-android:mergeDebugAssets
:sample-integration-android:generateDebugResValues UP-TO-DATE
:sample-integration-android:generateDebugResources
:sample-integration-android:mergeDebugResources
:sample-integration-android:processDebugManifest
:sample-integration-android:processDebugResources
:sample-integration-android:generateDebugSources
:sample-integration-android:processDebugJavaRes UP-TO-DATE
:sample-integration-android:compileDebugJavaWithJavac
:sample-integration-android:compileDebugNdk UP-TO-DATE
:sample-integration-android:compileDebugSources
> Building 40% > :sample-integration-android:preDexDebug 

why stop here can't go next???

**Comment by HashEngineering** [comment]
I don't know why it stops there.

**Comment by ywzqhl** [comment]
can you write a detail build guidline?thanke you very much!

**Comment by HashEngineering** [comment]
https://github.com/HashEngineering/darkcoin-wallet/blob/release-4/README.md

The bottom of this file has a simple guide.

**Comment by ywzqhl** [comment]
I already build success, but realease version can't be installed!others are nomarl! there is 'android-10' or 'android-16' in file  sample-integration-android/build.gradle at line 14,column 23.'android-10'  can't be installed on windows 7  x64.

**Comment by HashEngineering** [comment]
These instructions do not include zipaligning and signing the release versions that will actually run on the android.

**Comment by ywzqhl** [comment]
Yes,but how can I do? can you teach me?

**Comment by HashEngineering** [comment]
I currently use Android Studio to handle building and signing the apk.

Here are instructions using the commandline:
http://developer.android.com/tools/publishing/app-signing.html#signing-manually

**Comment by ywzqhl** [comment]
thank you very much,I will have a try!
