### ISSUE TITLE
Running this command failed giving some build exceptions - gradle clean :native-scrypt:copy test build 

### ISSUE THREAD

**Issue by chetanya19** [HashEngineering/dash-wallet#97]
![screenshot from 2018-03-27 12 18 50](https://user-images.githubusercontent.com/28563010/37951167-1a5b1078-31b9-11e8-9127-39a4facee8ae.png)

**Comment by HashEngineering** [comment]
We have not seen this error before.  Are you still getting it?

**Comment by HashEngineering** [comment]
Changes were made to the build system and this question is no longer applicable.
